// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKC7uAbBCZKA5EFRxMp89kbaMcZ-enoc',
    appId: '1:392326316941:web:404efa472b7331d5d633c4',
    messagingSenderId: '392326316941',
    projectId: 'flutter-app-3ab84',
    authDomain: 'flutter-app-3ab84.firebaseapp.com',
    databaseURL: 'https://flutter-app-3ab84.firebaseio.com',
    storageBucket: 'flutter-app-3ab84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5mjPlBGEIzLZmGv4Gez3vs11LIz_3qc',
    appId: '1:392326316941:android:b4554f12b0bbb45ad633c4',
    messagingSenderId: '392326316941',
    projectId: 'flutter-app-3ab84',
    databaseURL: 'https://flutter-app-3ab84.firebaseio.com',
    storageBucket: 'flutter-app-3ab84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQaotIrI9xML2GrouVgbbZf6ZsoW37J44',
    appId: '1:392326316941:ios:4af56a6a1d31b9f6d633c4',
    messagingSenderId: '392326316941',
    projectId: 'flutter-app-3ab84',
    databaseURL: 'https://flutter-app-3ab84.firebaseio.com',
    storageBucket: 'flutter-app-3ab84.appspot.com',
    iosBundleId: 'com.example.testGithubAction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQaotIrI9xML2GrouVgbbZf6ZsoW37J44',
    appId: '1:392326316941:ios:5d0b69fbd1405d5bd633c4',
    messagingSenderId: '392326316941',
    projectId: 'flutter-app-3ab84',
    databaseURL: 'https://flutter-app-3ab84.firebaseio.com',
    storageBucket: 'flutter-app-3ab84.appspot.com',
    iosBundleId: 'com.example.testGithubAction.RunnerTests',
  );
}
